### ISSUE TITLE
Knowledge is for everyone 

### ISSUE THREAD

**Issue by HelmiDev03** [yaya2devops/bachelor-guide#48]
This is high quality drive link  that can be useful for  isi and 2nd iot students:
https://drive.google.com/drive/folders/1UqYUhxtPWwYQpPaxtXZc3EhlTFVoMSDv

**Comment by yaya2devops** [comment]
This is great Helmi<br> Also I see you are doing **IOT**!

Can you do something here;

```
📁IOT/
├── 📁Semester3-IOT/
│   └── 3.md
├── 📁Semester4-IOT/
│   └── 4.md
└── 📁Semester5-IOT/
    └── 5.md
```

**Comment by HelmiDev03** [comment]
CE2(computer engineering 2nd year(iot) ) déja9 fih S3 w S4 men barcha uni
Same for CE1
I don't have S5 for now

**Comment by yaya2devops** [comment]
Np good luck on ur studies!
